// <auto-generated />
using System;
using AR_PROGRESO1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AR_PROGRESO1.Migrations
{
    [DbContext(typeof(AR_PROGRESO1Context))]
    [Migration("20230424133302_ARBase")]
    partial class ARBase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AR_PROGRESO1.Models.ARAURA", b =>
                {
                    b.Property<int>("arCodigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("arCodigo"), 1L, 1);

                    b.Property<decimal>("arCalificacionFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("arCodigoPostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("arCorreo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("arEstudianteNuevo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("arFechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("arNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float>("arPromedioConducta")
                        .HasColumnType("real");

                    b.HasKey("arCodigo");

                    b.ToTable("ARAURA");
                });
#pragma warning restore 612, 618
        }
    }
}
